version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: client_manager_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
